// Pricing tier data for the landing page
export const pricingTiers = [
  {
    name: "Brand Blueprint",
    price: "£2,600",
    description: "Perfect for founders ready to take their first step into vertical content creation.",
    buttonText: "Get Blueprint",
    buttonLink: "#pricing-blueprint",
    color: "#f97316",
    features: [
      "All essential founder must-watch basics",
      "Basic library for editors & social managers",
      "Lifetime Access to All Content",
      "4 weeks of Group Q&A Calls",
      "Condensed Monetization & Conversions Pro Series",
      "2 weeks email support",
      "Updates for 3-6 months"
    ],
    featureDetails: {
      "Core Founder Modules": "All essential founder must-watch basics",
      "Team Training Modules": "Basic library for editors & social managers",
      "Lifetime Access to All Content": "Yes",
      "Weekly Group Q&A Calls": "4 weeks total",
      "Private Community": "No",
      "Advanced Pipeline Templates": "No",
      "Done-With-You Pipeline Setup": "No",
      "1-on-1 Strategy Calls": "No",
      "Team Onboarding & Mentorship": "No",
      "Brand-Specific Content Audit": "No",
      "Monetization & Conversions Pro Series": "Condensed version",
      "Extended Support Window": "2 weeks email",
      "Lifetime Updates / New Modules": "Updates for 3-6 months",
      "Data/Analytics Training for Team": "No",
      "Copy & Hook Bank": "No",
      "Offline/Virtual Workshop": "No",
      "One-on-One Founder Vision Session": "No"
    }
  },
  {
    name: "Authority Autopilot",
    price: "£4,600",
    description: "The complete system for serious founders ready to dominate short-form content.",
    buttonText: "Get Builder",
    buttonLink: "#pricing-builder",
    popular: true,
    color: "#38bdf8",
    features: [
      "Full set of advanced strategic modules",
      "Extended library with advanced lessons",
      "Lifetime Access to All Content",
      "8-12 weeks of Group Q&A Calls",
      "Standard channel access to private community",
      "Ready-to-use pipeline templates",
      "1-2 private strategy sessions",
      "Group calls for your team",
      "Initial brand/content audit",
      "Full set of advanced monetization strategies",
      "4 weeks priority support",
      "1-2 years of free updates",
      "Basic analytics overview for team",
      "Full library of tested hooks and copy"
    ],
    featureDetails: {
      "Core Founder Modules": "Full set (including advanced strategic modules)",
      "Team Training Modules": "Extended library with advanced lessons",
      "Lifetime Access to All Content": "Yes",
      "Weekly Group Q&A Calls": "8-12 weeks total",
      "Private Community": "Standard channel access",
      "Advanced Pipeline Templates": "Ready-to-use templates",
      "Done-With-You Pipeline Setup": "No",
      "1-on-1 Strategy Calls": "1-2 private sessions",
      "Team Onboarding & Mentorship": "Group calls for the team, Slack Q&A",
      "Brand-Specific Content Audit": "One initial brand/content audit",
      "Monetization & Conversions Pro Series": "Full set of advanced strategies",
      "Extended Support Window": "4 weeks priority",
      "Lifetime Updates / New Modules": "1-2 years of free updates",
      "Data/Analytics Training for Team": "Basic analytics overview",
      "Copy & Hook Bank": "Full library of tested hooks and copy",
      "Offline/Virtual Workshop": "No",
      "One-on-One Founder Vision Session": "No"
    }
  },
  {
    name: "Viral Growth Engine",
    price: "£7,600",
    description: "The ultimate authority-building system with hands-on implementation support.",
    buttonText: "Get Growth Engine",
    buttonLink: "#pricing-accelerate",
    color: "#fb7185",
    features: [
      "Full set plus exclusive case studies",
      "Everything + specialized training for additional roles",
      "Lifetime Access + free updates forever",
      "16+ weeks of Group Q&A Calls",
      "Priority channel access with direct messaging",
      "Templates + custom adjustments by our team",
      "Hands-on help to configure & test",
      "Weekly or on-demand strategy sessions",
      "Dedicated mentorship for each key team member",
      "Initial + monthly ongoing audits",
      "Full monetization strategies + personalized coaching",
      "8+ weeks rolling priority support",
      "Lifetime updates with beta access",
      "Deep-dive training + monthly data interpretation",
      "Full hook library + monthly additions + custom suggestions",
      "1-day virtual workshop with you or your team",
      "In-depth brand vision session"
    ],
    featureDetails: {
      "Core Founder Modules": "Full set plus exclusive case studies",
      "Team Training Modules": "Everything + specialized training for additional roles",
      "Lifetime Access to All Content": "Yes, plus free updates forever",
      "Weekly Group Q&A Calls": "16+ weeks or indefinite while enrolled",
      "Private Community": "Priority channel with direct messaging to coaches",
      "Advanced Pipeline Templates": "Templates + custom adjustments by our team",
      "Done-With-You Pipeline Setup": "Hands-on help to configure & test for your brand",
      "1-on-1 Strategy Calls": "Weekly or on-demand sessions",
      "Team Onboarding & Mentorship": "Dedicated mentorship for each key team member",
      "Brand-Specific Content Audit": "Initial + monthly ongoing audits",
      "Monetization & Conversions Pro Series": "Full + personalized coaching calls",
      "Extended Support Window": "8+ weeks rolling priority support",
      "Lifetime Updates / New Modules": "Lifetime updates with beta access",
      "Data/Analytics Training for Team": "Deep-dive training + monthly interpretation",
      "Copy & Hook Bank": "Library + monthly additions + custom suggestions",
      "Offline/Virtual Workshop": "1-day virtual workshop with you or your team",
      "One-on-One Founder Vision Session": "In-depth brand vision session"
    }
  }
]; 